export const FETCH_CURRENCIES_REQUEST = 'FETCH_CURRENCIES_REQUEST';
export const FETCH_CURRENCIES_SUCCESS = 'FETCH_CURRENCIES_SUCCESS';
export const FETCH_CURRENCIES_FAILURE = 'FETCH_CURRENCIES_FAILURE';
export const LOADING = 'LOADING';
export const SET_EXCHANGE = 'SET_EXCHANGE';
export const TOGGLE_EXCHANGE_METHOD = 'TOGGLE_EXCHANGE_METHOD';