import Foundation

/// ISO 4217 numeric code -> (alpha code, minor digits, English name), generated from the `currency-codes` npm package
/// the web app uses. Keys are zero-padded ("008") exactly like that package.
nonisolated enum ISO4217 {
    static let byNumber: [String: (code: String, digits: Int, name: String)] = [
        "784": ("AED", 2, "UAE Dirham"),
        "971": ("AFN", 2, "Afghani"),
        "008": ("ALL", 2, "Lek"),
        "051": ("AMD", 2, "Armenian Dram"),
        "532": ("ANG", 2, "Netherlands Antillean Guilder"),
        "973": ("AOA", 2, "Kwanza"),
        "032": ("ARS", 2, "Argentine Peso"),
        "036": ("AUD", 2, "Australian Dollar"),
        "533": ("AWG", 2, "Aruban Florin"),
        "944": ("AZN", 2, "Azerbaijan Manat"),
        "977": ("BAM", 2, "Convertible Mark"),
        "052": ("BBD", 2, "Barbados Dollar"),
        "050": ("BDT", 2, "Taka"),
        "975": ("BGN", 2, "Bulgarian Lev"),
        "048": ("BHD", 3, "Bahraini Dinar"),
        "108": ("BIF", 0, "Burundi Franc"),
        "060": ("BMD", 2, "Bermudian Dollar"),
        "096": ("BND", 2, "Brunei Dollar"),
        "068": ("BOB", 2, "Boliviano"),
        "984": ("BOV", 2, "Mvdol"),
        "986": ("BRL", 2, "Brazilian Real"),
        "044": ("BSD", 2, "Bahamian Dollar"),
        "064": ("BTN", 2, "Ngultrum"),
        "072": ("BWP", 2, "Pula"),
        "933": ("BYN", 2, "Belarusian Ruble"),
        "084": ("BZD", 2, "Belize Dollar"),
        "124": ("CAD", 2, "Canadian Dollar"),
        "976": ("CDF", 2, "Congolese Franc"),
        "947": ("CHE", 2, "WIR Euro"),
        "756": ("CHF", 2, "Swiss Franc"),
        "948": ("CHW", 2, "WIR Franc"),
        "990": ("CLF", 4, "Unidad de Fomento"),
        "152": ("CLP", 0, "Chilean Peso"),
        "156": ("CNY", 2, "Yuan Renminbi"),
        "170": ("COP", 2, "Colombian Peso"),
        "970": ("COU", 2, "Unidad de Valor Real"),
        "188": ("CRC", 2, "Costa Rican Colon"),
        "931": ("CUC", 2, "Peso Convertible"),
        "192": ("CUP", 2, "Cuban Peso"),
        "132": ("CVE", 2, "Cabo Verde Escudo"),
        "203": ("CZK", 2, "Czech Koruna"),
        "262": ("DJF", 0, "Djibouti Franc"),
        "208": ("DKK", 2, "Danish Krone"),
        "214": ("DOP", 2, "Dominican Peso"),
        "012": ("DZD", 2, "Algerian Dinar"),
        "818": ("EGP", 2, "Egyptian Pound"),
        "232": ("ERN", 2, "Nakfa"),
        "230": ("ETB", 2, "Ethiopian Birr"),
        "978": ("EUR", 2, "Euro"),
        "242": ("FJD", 2, "Fiji Dollar"),
        "238": ("FKP", 2, "Falkland Islands Pound"),
        "826": ("GBP", 2, "Pound Sterling"),
        "981": ("GEL", 2, "Lari"),
        "936": ("GHS", 2, "Ghana Cedi"),
        "292": ("GIP", 2, "Gibraltar Pound"),
        "270": ("GMD", 2, "Dalasi"),
        "324": ("GNF", 0, "Guinean Franc"),
        "320": ("GTQ", 2, "Quetzal"),
        "328": ("GYD", 2, "Guyana Dollar"),
        "344": ("HKD", 2, "Hong Kong Dollar"),
        "340": ("HNL", 2, "Lempira"),
        "191": ("HRK", 2, "Kuna"),
        "332": ("HTG", 2, "Gourde"),
        "348": ("HUF", 2, "Forint"),
        "360": ("IDR", 2, "Rupiah"),
        "376": ("ILS", 2, "New Israeli Sheqel"),
        "356": ("INR", 2, "Indian Rupee"),
        "368": ("IQD", 3, "Iraqi Dinar"),
        "364": ("IRR", 2, "Iranian Rial"),
        "352": ("ISK", 0, "Iceland Krona"),
        "388": ("JMD", 2, "Jamaican Dollar"),
        "400": ("JOD", 3, "Jordanian Dinar"),
        "392": ("JPY", 0, "Yen"),
        "404": ("KES", 2, "Kenyan Shilling"),
        "417": ("KGS", 2, "Som"),
        "116": ("KHR", 2, "Riel"),
        "174": ("KMF", 0, "Comorian Franc "),
        "408": ("KPW", 2, "North Korean Won"),
        "410": ("KRW", 0, "Won"),
        "414": ("KWD", 3, "Kuwaiti Dinar"),
        "136": ("KYD", 2, "Cayman Islands Dollar"),
        "398": ("KZT", 2, "Tenge"),
        "418": ("LAK", 2, "Lao Kip"),
        "422": ("LBP", 2, "Lebanese Pound"),
        "144": ("LKR", 2, "Sri Lanka Rupee"),
        "430": ("LRD", 2, "Liberian Dollar"),
        "426": ("LSL", 2, "Loti"),
        "434": ("LYD", 3, "Libyan Dinar"),
        "504": ("MAD", 2, "Moroccan Dirham"),
        "498": ("MDL", 2, "Moldovan Leu"),
        "969": ("MGA", 2, "Malagasy Ariary"),
        "807": ("MKD", 2, "Denar"),
        "104": ("MMK", 2, "Kyat"),
        "496": ("MNT", 2, "Tugrik"),
        "446": ("MOP", 2, "Pataca"),
        "929": ("MRU", 2, "Ouguiya"),
        "480": ("MUR", 2, "Mauritius Rupee"),
        "462": ("MVR", 2, "Rufiyaa"),
        "454": ("MWK", 2, "Malawi Kwacha"),
        "484": ("MXN", 2, "Mexican Peso"),
        "979": ("MXV", 2, "Mexican Unidad de Inversion (UDI)"),
        "458": ("MYR", 2, "Malaysian Ringgit"),
        "943": ("MZN", 2, "Mozambique Metical"),
        "516": ("NAD", 2, "Namibia Dollar"),
        "566": ("NGN", 2, "Naira"),
        "558": ("NIO", 2, "Cordoba Oro"),
        "578": ("NOK", 2, "Norwegian Krone"),
        "524": ("NPR", 2, "Nepalese Rupee"),
        "554": ("NZD", 2, "New Zealand Dollar"),
        "512": ("OMR", 3, "Rial Omani"),
        "590": ("PAB", 2, "Balboa"),
        "604": ("PEN", 2, "Sol"),
        "598": ("PGK", 2, "Kina"),
        "608": ("PHP", 2, "Philippine Peso"),
        "586": ("PKR", 2, "Pakistan Rupee"),
        "985": ("PLN", 2, "Zloty"),
        "600": ("PYG", 0, "Guarani"),
        "634": ("QAR", 2, "Qatari Rial"),
        "946": ("RON", 2, "Romanian Leu"),
        "941": ("RSD", 2, "Serbian Dinar"),
        "643": ("RUB", 2, "Russian Ruble"),
        "646": ("RWF", 0, "Rwanda Franc"),
        "682": ("SAR", 2, "Saudi Riyal"),
        "090": ("SBD", 2, "Solomon Islands Dollar"),
        "690": ("SCR", 2, "Seychelles Rupee"),
        "938": ("SDG", 2, "Sudanese Pound"),
        "752": ("SEK", 2, "Swedish Krona"),
        "702": ("SGD", 2, "Singapore Dollar"),
        "654": ("SHP", 2, "Saint Helena Pound"),
        "694": ("SLL", 2, "Leone"),
        "706": ("SOS", 2, "Somali Shilling"),
        "968": ("SRD", 2, "Surinam Dollar"),
        "728": ("SSP", 2, "South Sudanese Pound"),
        "930": ("STN", 2, "Dobra"),
        "222": ("SVC", 2, "El Salvador Colon"),
        "760": ("SYP", 2, "Syrian Pound"),
        "748": ("SZL", 2, "Lilangeni"),
        "764": ("THB", 2, "Baht"),
        "972": ("TJS", 2, "Somoni"),
        "934": ("TMT", 2, "Turkmenistan New Manat"),
        "788": ("TND", 3, "Tunisian Dinar"),
        "776": ("TOP", 2, "Pa’anga"),
        "949": ("TRY", 2, "Turkish Lira"),
        "780": ("TTD", 2, "Trinidad and Tobago Dollar"),
        "901": ("TWD", 2, "New Taiwan Dollar"),
        "834": ("TZS", 2, "Tanzanian Shilling"),
        "980": ("UAH", 2, "Hryvnia"),
        "800": ("UGX", 0, "Uganda Shilling"),
        "840": ("USD", 2, "US Dollar"),
        "997": ("USN", 2, "US Dollar (Next day)"),
        "940": ("UYI", 0, "Uruguay Peso en Unidades Indexadas (UI)"),
        "858": ("UYU", 2, "Peso Uruguayo"),
        "927": ("UYW", 4, "Unidad Previsional"),
        "860": ("UZS", 2, "Uzbekistan Sum"),
        "928": ("VES", 2, "Bolívar Soberano"),
        "704": ("VND", 0, "Dong"),
        "548": ("VUV", 0, "Vatu"),
        "882": ("WST", 2, "Tala"),
        "950": ("XAF", 0, "CFA Franc BEAC"),
        "961": ("XAG", 0, "Silver"),
        "959": ("XAU", 0, "Gold"),
        "955": ("XBA", 0, "Bond Markets Unit European Composite Unit (EURCO)"),
        "956": ("XBB", 0, "Bond Markets Unit European Monetary Unit (E.M.U.-6)"),
        "957": ("XBC", 0, "Bond Markets Unit European Unit of Account 9 (E.U.A.-9)"),
        "958": ("XBD", 0, "Bond Markets Unit European Unit of Account 17 (E.U.A.-17)"),
        "951": ("XCD", 2, "East Caribbean Dollar"),
        "960": ("XDR", 0, "SDR (Special Drawing Right)"),
        "952": ("XOF", 0, "CFA Franc BCEAO"),
        "964": ("XPD", 0, "Palladium"),
        "953": ("XPF", 0, "CFP Franc"),
        "962": ("XPT", 0, "Platinum"),
        "994": ("XSU", 0, "Sucre"),
        "963": ("XTS", 0, "Codes specifically reserved for testing purposes"),
        "965": ("XUA", 0, "ADB Unit of Account"),
        "999": ("XXX", 0, "The codes assigned for transactions where no currency is involved"),
        "886": ("YER", 2, "Yemeni Rial"),
        "710": ("ZAR", 2, "Rand"),
        "967": ("ZMW", 2, "Zambian Kwacha"),
        "932": ("ZWL", 2, "Zimbabwe Dollar"),
    ]
}
